version: "3.9"
services:
  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_DB=0
      - REDIS_MAXMEMORY=256mb

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  # pgadmin with no authentication
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-changeme}
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

  minio:
    image: quay.io/minio/minio
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio:/data

volumes:
  postgres:
  minio:
  pgadmin:
  redis:
