version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres:
