CREATE DATABASE auth;
CREATE DATABASE keys;
CREATE DATABASE qr;
GRANT ALL PRIVILEGES ON DATABASE auth TO "postgres";
GRANT ALL PRIVILEGES ON DATABASE keys TO "postgres";
GRANT ALL PRIVILEGES ON DATABASE qr TO "postgres";
