version: "3.9"
# redis docker service
services:
  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_DB=0
      - REDIS_MAXMEMORY=256mb

volumes:
  redis:
